import { PAGES_IT } from "../PagesConst";
export const CONTATTI = {
  it: {
    title: "Contatti",
    subtitle:
      "Diverse **location**, diversi **menù**, diverse **squadre**, una filosofia in comune: <br> offrirvi un'**esperienza** da ricordare.",
    otherContatti:
      "**EVENTI**: <a href='mailto:eventi@vivavivianavarese.it'>eventi@vivavivianavarese.it</a> <br> **PRESS OFFICE**: <a href='mailto:comunicazione@vivavivianavarese.it'>comunicazione@vivavivianavarese.it</a> <br> **LAVORA CON NOI**: <a href='mailto:job@vivavivianavarese.it'>job@vivavivianavarese.it</a>",
    newsletter: "> Iscriviti alla nostra newsletter <",
    visitUs: "Vieni a trovarci",
    array: [
      {
        title: "VIVIA Viviana Varese - 1 stella michelin",
        location: "MILANO",
        srcLogo: "contatti/logo-viva.jpg",
        alt: "Viva",
        bcolor: "rgba(228,34,129, 0.8)",
        href: PAGES_IT.VIVA.slug,
        address:
          "2° piano di Eataly Smeraldo - Piazza 25 Aprile, 10 – 20121 Milano",
        tel: "<a href='tel:+390249497340'>+39 02 4949 7340</a>",
        mail: "<a href='mailto:info@vivavivianavarese.it'>info@vivavivianavarese.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://goo.gl/maps/tRNN7PdhEchcAJKUA",
        instagram: "https://www.instagram.com/vivavivianavarese/?hl=it",
      },
      {
        title: "W VILLADORATA Country Restaurant",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo_villadorata.jpg",
        alt: "Villadorata",
        bcolor: "rgb(232,204,114, 0.7)",
        href: PAGES_IT.VILLADORATA.slug,
        address: "Contrada Portelle, Noto (SR)",
        tel: "<a href='tel:+393428163083'>+39 342 8163083</a>",
        mail: "<a href='mailto:villadorata@vivavivianavarese.it'>villadorata@vivavivianavarese.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://goo.gl/maps/y5U26yAijbcTiHk96",
        instagram:
          "https://www.instagram.com/wvilladorata/?igshid=19oq9l39w4yqb,",
      },
      {
        title: "VIVA IL BISTROT",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo-bistrot.jpg",
        alt: "Bistrot",
        bcolor: "rgba(194,133,106, 0.7)",
        href: PAGES_IT.BISTROT.slug,
        address: "Via Rocco Pirri 19, Noto (SR)",
        tel: "<a href='tel:+393347933384'>+39 334 7933384</a>",
        mail: "<a href='mailto:vivabistrot@vivavivianavarese.it'>vivabistrot@vivavivianavarese.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://goo.gl/maps/PJJFTFfkhusi7NUx6",
        instagram: "https://www.instagram.com/viva_ilbistrotnoto/",
      },
      {
        title: "POLPO - Semplicemente Pesce",
        location: "MILANO",
        srcLogo: "contatti/logo-polpo-blu.jpg",
        alt: "polpopesce",
        bcolor: "rgba(47,56,136, 1)",
        href: "http://polpopesce.it/",
        address: "Via Melzo 9, 20129 Milano (MI)",
        tel: "<a href='tel:+390284572974'>+39 02 84572974</a> / <a href='tel:+393423926392'>+39 3423926392</a>",
        mail: "<a href='mailto:info@polpopesce.it'>info@polpopesce.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://maps.app.goo.gl/Q2xPA26mrcxBZXpTA",
        instagram: "https://www.instagram.com/polpopesce/",
      },
    ],
  },
  en: {
    title: "Contacts",
    subtitle:
      "Different **locations**, different **menus**, different **teams**, a common philosophy: <br> to offer you an **experience** to remember.",
    otherContatti:
      "**EVENTS**: <a href='mailto:eventi@vivavivianavarese.it'>eventi@vivavivianavarese.it</a> <br> **PRESS OFFICE**: <a href='mailto:comunicazione@vivavivianavarese.it'>comunicazione@vivavivianavarese.it</a> <br> **WORK WITH US**: <a href='mailto:job@vivavivianavarese.it'>job@vivavivianavarese.it</a>",
    newsletter: "> Sign up to our newsletter <",
    visitUs: "Come visit us",
    array: [
      {
        title: "VIVIA Viviana Varese - 1 Michelin star",
        location: "MILANO",
        srcLogo: "contatti/logo-viva.jpg",
        alt: "Viva",
        bcolor: "rgba(228,34,129, 0.8)",
        href: PAGES_IT.VIVA.slug,
        address:
          "2° floor Eataly Smeraldo - Square 25 Aprile, 10 – 20121 Milano",
        tel: "<a href='tel:+390249497340'>+39 02 4949 7340</a>",
        mail: "<a href='mailto:info@vivavivianavarese.it'>info@vivavivianavarese.it</a>",
        seeMap: "See map",
        linkMap: "https://goo.gl/maps/tRNN7PdhEchcAJKUA",
        instagram: "https://www.instagram.com/vivavivianavarese/?hl=it",
      },
      {
        title: "W VILLADORATA Country Restaurant",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo_villadorata.jpg",
        alt: "Villadorata",
        bcolor: "rgb(232,204,114, 0.7)",
        href: PAGES_IT.VILLADORATA.slug,
        address: "Contrada Portelle, Noto (SR)",
        tel: "<a href='tel:+393428163083'>+39 342 8163083</a>",
        mail: "<a href='mailto:villadorata@vivavivianavarese.it'>villadorata@vivavivianavarese.it</a>",
        seeMap: "See map",
        linkMap: "https://goo.gl/maps/y5U26yAijbcTiHk96",
        instagram:
          "https://www.instagram.com/wvilladorata/?igshid=19oq9l39w4yqb,",
      },
      {
        title: "VIVA IL BISTROT",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo-bistrot.jpg",
        alt: "Bistrot",
        bcolor: "rgba(194,133,106, 0.7)",
        href: PAGES_IT.BISTROT.slug,
        address: "Street Rocco Pirri 19, Noto (SR)",
        tel: "<a href='tel:+393347933384'>+39 334 7933384</a>",
        mail: "<a href='mailto:vivabistrot@vivavivianavarese.it'>vivabistrot@vivavivianavarese.it</a>",
        seeMap: "See map",
        linkMap: "https://goo.gl/maps/PJJFTFfkhusi7NUx6",
        instagram: "https://www.instagram.com/viva_ilbistrotnoto/",
      },
      {
        title: "POLPO - Semplicemente Pesce",
        location: "MILANO",
        srcLogo: "contatti/logo-polpo-blu.jpg",
        alt: "polpopesce",
        bcolor: "rgba(47,56,136, 1)",
        href: "http://polpopesce.it/",
        address: "Street Melzo 9, 20129 Milano (MI)",
        tel: "<a href='tel:+390284572974'>+39 02 84572974</a> / <a href='tel:+393423926392'>+39 3423926392</a>",
        mail: "<a href='mailto:info@polpopesce.it'>info@polpopesce.it</a>",
        seeMap: "See map",
        linkMap: "https://maps.app.goo.gl/Q2xPA26mrcxBZXpTA",
        instagram: "https://www.instagram.com/polpopesce/",
      },
    ],
  },
};
