import { PAGES_IT } from "../PagesConst";
export const CONTATTI = {
  it: {
    title: "Contatti",
    subtitle:
      "Diverse **location**, diversi **menù**, diverse **squadre**, una filosofia in comune: <br> offrirvi un'**esperienza** da ricordare.",
    otherContatti:
      "**EVENTI E COMUNICAZIONE**: <a href='mailto:eventi@vivianavaresechef.it'>eventi@vivianavaresechef.it</a> <br> **LAVORA CON NOI**: <a href='mailto:info@vivianavaresechef.it'>info@vivianavaresechef.it</a>",
    newsletter: "> Iscriviti alla nostra newsletter <",
    visitUs: "Vieni a trovarci",
    array: [
      {
        title: "W VILLADORATA Country Restaurant",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo_villadorata.jpg",
        alt: "Villadorata",
        bcolor: "rgb(232,204,114, 0.7)",
        href: PAGES_IT.VILLADORATA.slug,
        address: "Contrada Portelle, Noto (SR)",
        tel: "<a href='tel:+393428163083'>+39 342 8163083</a>",
        mail: "<a href='mailto:villadorata@vivianavaresechef.it'>villadorata@vivianavaresechef.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://goo.gl/maps/y5U26yAijbcTiHk96",
        instagram:
          "https://www.instagram.com/wvilladorata/?igshid=19oq9l39w4yqb,",
      },
      {
        title: "VIVA IL BISTROT",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo-bistrot.jpg",
        alt: "Bistrot",
        bcolor: "rgba(194,133,106, 0.7)",
        href: PAGES_IT.BISTROT.slug,
        address: "Via Rocco Pirri 19, Noto (SR)",
        tel: "<a href='tel:+393347933384'>+39 334 7933384</a>",
        mail: "<a href='mailto:vivabistrot@vivianavaresechef.it'>vivabistrot@vivianavaresechef.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://goo.gl/maps/PJJFTFfkhusi7NUx6",
        instagram: "https://www.instagram.com/viva_ilbistrotnoto/",
      },
      {
        title: "POLPO - Semplicemente Pesce",
        location: "MILANO",
        srcLogo: "contatti/logo-polpo-blu.jpg",
        alt: "polpopesce",
        bcolor: "rgba(47,56,136, 1)",
        href: PAGES_IT.POLPO.slug,
        address: "Via Melzo 9, 20129 Milano (MI)",
        tel: "<a href='tel:+390284572974'>+39 02 84572974</a> / <a href='tel:+393423926392'>+39 3423926392</a>",
        mail: "<a href='mailto:info@polpopesce.it'>info@polpopesce.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://maps.app.goo.gl/Q2xPA26mrcxBZXpTA",
        instagram: "https://www.instagram.com/polpopesce/",
      },
      {
        title: "FAAK Cibo e Vino a ribellione naturale",
        location: "MILANO",
        srcLogo: "contatti/logo-faak.jpg",
        alt: "faak",
        bcolor: "#b03d18",
        href: PAGES_IT.FAAK.slug,
        address: "Via Arnaldo Da Brescia, 5 – 20159 Milano",
        tel: "<a href='tel:+393401352676'>+39 340 1352676</a>",
        mail: "<a href='mailto:info@faakfaak.it'>info@faakfaak.it</a>",
        seeMap: "Vedi mappa",
        linkMap: "https://maps.app.goo.gl/jPPBPUoANfezVpvg7",
        instagram: "https://www.instagram.com/faakfuoco/",
      },
      {
        title: "PASSALACQUA",
        location: "Moltrasio, Lago di Como",
        srcLogo: "contatti/logo-passalacqua.jpg",
        alt: "passalacqua",
        bcolor: "rgb(226,171,59)",
        href: PAGES_IT.PASSALACQUA.slug,
        address: "Via Besana, 59, 22010 Moltrasio, CO",
        tel: "<a href='tel:+3903144311'>+39 031 44311</a>",
        mail: "<a href='mailto:foryou@passalacqua.it'>foryou@passalacqua.it</a> <br> Per prenotazioni al ristorante: <a href='mailto:restaurant@passalacqua.it'>restaurant@passalacqua.it</a> ",
        seeMap: "Vedi mappa",
        linkMap: "https://maps.app.goo.gl/FdH8bLiiPjp3HYsS9",
        instagram: "https://www.instagram.com/passalacqualakecomo",
      },
    ],
  },
  en: {
    title: "Contacts",
    subtitle:
      "Different **locations**, different **menus**, different **teams**, a common philosophy: <br> to offer you an **experience** to remember.",
    otherContatti:
      "**EVENTS AND COMMUNICATION**: <a href='mailto:eventi@vivianavaresechef.it'>eventi@vivianavaresechef.it</a> <br> **WORK WITH US**: <a href='mailto:info@vivianavaresechef.it'>info@vivianavaresechef.it</a>",
    newsletter: "> Sign up to our newsletter <",
    visitUs: "Come visit us",
    array: [
      {
        title: "W VILLADORATA Country Restaurant",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo_villadorata.jpg",
        alt: "Villadorata",
        bcolor: "rgb(232,204,114, 0.7)",
        href: PAGES_IT.VILLADORATA.slug,
        address: "Contrada Portelle, Noto (SR)",
        tel: "<a href='tel:+393428163083'>+39 342 8163083</a>",
        mail: "<a href='mailto:villadorata@vivianavaresechef.it'>villadorata@vivianavaresechef.it</a>",
        seeMap: "See map",
        linkMap: "https://goo.gl/maps/y5U26yAijbcTiHk96",
        instagram:
          "https://www.instagram.com/wvilladorata/?igshid=19oq9l39w4yqb,",
      },
      {
        title: "VIVA IL BISTROT",
        location: "NOTO, Sicilia",
        srcLogo: "contatti/logo-bistrot.jpg",
        alt: "Bistrot",
        bcolor: "rgba(194,133,106, 0.7)",
        href: PAGES_IT.BISTROT.slug,
        address: "Street Rocco Pirri 19, Noto (SR)",
        tel: "<a href='tel:+393347933384'>+39 334 7933384</a>",
        mail: "<a href='mailto:vivabistrot@vivianavaresechef.it'>vivabistrot@vivianavaresechef.it</a>",
        seeMap: "See map",
        linkMap: "https://goo.gl/maps/PJJFTFfkhusi7NUx6",
        instagram: "https://www.instagram.com/viva_ilbistrotnoto/",
      },
      {
        title: "POLPO - Semplicemente Pesce",
        location: "MILANO",
        srcLogo: "contatti/logo-polpo-blu.jpg",
        alt: "polpopesce",
        bcolor: "rgba(47,56,136, 1)",
        href: PAGES_IT.POLPO.slug,
        address: "Street Melzo 9, 20129 Milano (MI)",
        tel: "<a href='tel:+390284572974'>+39 02 84572974</a> / <a href='tel:+393423926392'>+39 3423926392</a>",
        mail: "<a href='mailto:info@polpopesce.it'>info@polpopesce.it</a>",
        seeMap: "See map",
        linkMap: "https://maps.app.goo.gl/Q2xPA26mrcxBZXpTA",
        instagram: "https://www.instagram.com/polpopesce/",
      },
      {
        title: "FAAK Naturally rebellious food and wine",
        location: "MILANO",
        srcLogo: "contatti/logo-faak.jpg",
        alt: "faak",
        bcolor: "#b03d18",
        href: PAGES_IT.FAAK.slug,
        address: "Via Arnaldo Da Brescia, 5 – 20159 Milano",
        tel: "<a href='tel:+393401352676'>+39 340 1352676</a>",
        mail: "<a href='mailto:info@faakfaak.it'>info@faakfaak.it</a>",
        seeMap: "See map",
        linkMap: "https://maps.app.goo.gl/jPPBPUoANfezVpvg7",
        instagram: "https://www.instagram.com/faakfuoco/",
      },
      {
        title: "PASSALACQUA",
        location: "Moltrasio, Como Lake",
        srcLogo: "contatti/logo-passalacqua.jpg",
        alt: "passalacqua",
        bcolor: "rgb(226,171,59)",
        href: PAGES_IT.PASSALACQUA.slug,
        address: "Via Besana, 59, 22010 Moltrasio, CO",
        tel: "<a href='tel:+3903144311'>+39 031 44311</a>",
        mail: "<a href='mailto:foryou@passalacqua.it'>foryou@passalacqua.it</a> <br> For reservations: <a href='mailto:restaurant@passalacqua.it'>restaurant@passalacqua.it</a> ",
        seeMap: "See map",
        linkMap: "https://maps.app.goo.gl/FdH8bLiiPjp3HYsS9",
        instagram: "https://www.instagram.com/passalacqualakecomo",
      },
    ],
  },
};
