export const PAGES_IT = {
  HOME: { name: "home", slug: "/", label: "HOME" },
  VIVIANA_VARESE: {
    name: "viviana",
    slug: "/viviana-varese",
    label: "VIVIANA VARESE",
    description: "",
  },
  VILLADORATA: {
    name: "villadorata",
    slug: "/viva-villadorata",
    label: "W Villadorata Country Restaurant",
    description: "Noto, Sicilia",
  },
  BISTROT: {
    name: "bistrot",
    slug: "/viva-il-bistrot",
    label: "VIVA IL BISTROT",
    description: "Noto, Sicilia",
  },
  POLPO: {
    name: "polpo",
    slug: "http://polpopesce.it/",
    label: "POLPO - Semplicemente pesce",
    description: "Milano",
    target: "_blank",
  },
  FAAK: {
    name: "faak",
    slug: "https://www.faakfaak.it/",
    label: "FAAK - Cibo e Vino a ribellione naturale",
    description: "Milano",
    target: "_blank",
  },
  PASSALACQUA: {
    name: "passalacqua",
    slug: "https://www.passalacqua.it/en/taste/",
    label: "PASSALACQUA",
    description: "Moltrasio, Lago di Como",
    target: "_blank",
  },
  EVENTI: {
    name: "eventi",
    slug: "/eventi",
    label: "GLI EVENTI",
  },
  WORK_WITH: {
    name: "work-with",
    slug: "/lavora-con-noi",
    label: "LAVORA CON NOI",
  },
  CONTATTI: {
    name: "contatti",
    slug: "/contatti",
    label: "CONTATTI",
  },
  SHOP_VIVA: {
    name: "shop-viva",
    slug: "https://ac80e3.myshopify.com/",
    label: "SHOP",
    target: "_blank",
  },
  SHOP_VILLADORATA: {
    name: "shop-villadorata",
    slug: "https://ac80e3.myshopify.com/",
    label: "SHOP VILLADORATA",
    target: "_blank",
  },
  PROGETTI: {
    name: "progetti",
    slug: "#",
    label: "I PROGETTI",
  },
};
export const PAGES_EN = {
  HOME: { name: "home", slug: "/", label: "HOME" },
  VIVIANA_VARESE: {
    name: "viviana",
    slug: "/viviana-varese",
    label: "VIVIANA VARESE",
  },
  VILLADORATA: {
    name: "villadorata",
    slug: "/viva-villadorata",
    label: "W Villadorata Country Restaurant",
    description: "Noto, Sicily",
  },
  BISTROT: {
    name: "bistrot",
    slug: "/viva-il-bistrot",
    label: "VIVA IL BISTROT",
    description: "Noto, Sicily",
  },
  POLPO: {
    name: "polpo",
    slug: "http://polpopesce.it/",
    label: "POLPO - Simply fish",
    description: "Milano",
    target: "_blank",
  },
  FAAK: {
    name: "faak",
    slug: "https://www.faakfaak.it/",
    label: "FAAK - Naturally rebellious food and wine",
    description: "Milano",
    target: "_blank",
  },
  PASSALACQUA: {
    name: "passalacqua",
    slug: "https://www.passalacqua.it/en/taste/",
    label: "PASSALACQUA",
    description: "Moltrasio, Como Lake",
    target: "_blank",
  },
  EVENTI: {
    name: "eventi",
    slug: "/eventi",
    label: "EVENTS",
  },
  WORK_WITH: {
    name: "work-with",
    slug: "/lavora-con-noi",
    label: "WORK WITH US",
  },
  CONTATTI: {
    name: "contatti",
    slug: "/contatti",
    label: "CONTACTS",
  },
  SHOP_VIVA: {
    name: "shop-viva",
    slug: "https://ac80e3.myshopify.com/",
    label: "SHOP",
    target: "_blank",
  },
  SHOP_VILLADORATA: {
    name: "shop-villadorata",
    slug: "https://ac80e3.myshopify.com/",
    label: "SHOP VILLADORATA",
    target: "_blank",
  },
  PROGETTI: {
    name: "projects",
    slug: "#",
    label: "PROJECTS",
  },
};
